/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLFilesquashWidgetElement extends HTMLStencilElement {
    'token': string;
  }
  var HTMLFilesquashWidgetElement: {
    prototype: HTMLFilesquashWidgetElement;
    new (): HTMLFilesquashWidgetElement;
  };
  interface HTMLElementTagNameMap {
    'filesquash-widget': HTMLFilesquashWidgetElement;
  }
  interface ElementTagNameMap {
    'filesquash-widget': HTMLFilesquashWidgetElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'filesquash-widget': JSXElements.FilesquashWidgetAttributes;
    }
  }
  namespace JSXElements {
    export interface FilesquashWidgetAttributes extends HTMLAttributes {
      'onUploadCompleted'?: (event: CustomEvent) => void;
      'token'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
